project:
  type: website
  
website: 
  title: "Lovelace Weekly Ops Report"
  site-url: "https://jeremydata.quarto.pub/quarto-custom-listing-cards"
  favicon: fav.png

format:
  html:
    theme:
       light: [simplex, custom.scss]
    fontsize: .9em
